variable "envr"{}
variable "ami"{}
variable "instanceType"{}
variable "component"{}
variable "type"{}
variable "user"{}
variable "password"{}
variable "securityname"{}
variable "route_zoneid"{}
variable "dnsrecordttl"{}