format_version: 10
pipelines:
  terraform-destroy:
    group: destroy
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/PavaniVemasani18/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          terraform-destroy:
            timeout: 0
            tasks:
            - exec: { command: terraform, arguments: ["init"], run_if: passed }
            - exec: { command: terraform, arguments: ["destroy","-var-file=env-dev/main.tfvars","-auto-approve"], run_if: passed }


