format_version: 10
pipelines:
  expense-teraform:
    group: terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36bac2c:
        git: https://github.com/PavaniVemasani18/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          terraform-apply:

            tasks:
            - exec:{command: terraform,arguments:["init","-backend-config=backend-env-dev/state.tfvars"]}
            - exec:{command: terraform,arguments:["apply","-var-file=backend-env-dev/main.tfvars"]}
                run_if: passed

